export const types = {
    //  Language
    SELECT_LANGUAGE_ENG: 'SELECT_LANGUAGE_ENG',
    SELECT_LANGUAGE_SPA: 'SELECT_LANGUAGE_SPA',
    //  Theme
    SELECT_DARK_THEME: 'SELECT_DARK_THEME',
    SELECT_LIGHT_THEME: 'SELECT_LIGHT_THEME'
}